"""empty message

Revision ID: 47bb58ac3663
Revises: cda0b457dc28
Create Date: 2023-08-08 16:09:02.920330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bb58ac3663'
down_revision: Union[str, None] = 'cda0b457dc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Numbers', 'ReqId', new_column_name='ReqID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Numbers', 'ReqID', new_column_name='ReqId')
    # ### end Alembic commands ###
